// backend/wordBank.ts
export interface WordPair {
  word: string;
  category: string;
}

export const WORD_BANK: WordPair[] = [
  // Famous People
{ word: "Aatrox", category: "Set 15 Unit" },
  { word: "Ahri", category: "Set 15 Unit" },
  { word: "Akali", category: "Set 15 Unit" },
  { word: "Ashe", category: "Set 15 Unit" },
  { word: "Braum", category: "Set 15 Unit" },
  { word: "Caitlyn", category: "Set 15 Unit" },
  { word: "Darius", category: "Set 15 Unit" },
  { word: "Ekko", category: "Set 15 Unit" },
  { word: "Ezreal", category: "Set 15 Unit" },
  { word: "Garen", category: "Set 15 Unit" },
  { word: "Gwen", category: "Set 15 Unit" },
  { word: "Janna", category: "Set 15 Unit" },
  { word: "Jarvan", category: "Set 15 Unit" },
  { word: "Jhin", category: "Set 15 Unit" },
  { word: "KSante", category: "Set 15 Unit" },
  { word: "Katarina", category: "Set 15 Unit" },
  { word: "Kayle", category: "Set 15 Unit" },
  { word: "Kennen", category: "Set 15 Unit" },
  { word: "Lux", category: "Set 15 Unit" },
  { word: "Malphite", category: "Set 15 Unit" },
  { word: "Malzahar", category: "Set 15 Unit" },
  { word: "Neeko", category: "Set 15 Unit" },
  { word: "Poppy", category: "Set 15 Unit" },
  { word: "Rakan", category: "Set 15 Unit" },
  { word: "Rell", category: "Set 15 Unit" },
  { word: "Ryze", category: "Set 15 Unit" },
  { word: "Samira", category: "Set 15 Unit" },
  { word: "Senna", category: "Set 15 Unit" },
  { word: "Seraphine", category: "Set 15 Unit" },
  { word: "Shen", category: "Set 15 Unit" },
  { word: "Sivir", category: "Set 15 Unit" },
  { word: "Swain", category: "Set 15 Unit" },
  { word: "Syndra", category: "Set 15 Unit" },
  { word: "Twisted Fate", category: "Set 15 Unit" },
  { word: "Udyr", category: "Set 15 Unit" },
  { word: "Varus", category: "Set 15 Unit" },
  { word: "Vi", category: "Set 15 Unit" },
  { word: "Viego", category: "Set 15 Unit" },
  { word: "Volibear", category: "Set 15 Unit" },
  { word: "Xayah", category: "Set 15 Unit" },
  { word: "Xin Zhao", category: "Set 15 Unit" },
  { word: "Yasuo", category: "Set 15 Unit" },
  { word: "Yone", category: "Set 15 Unit" },

  // TFT Set 15 Items
   { word: "Guinsoos Rageblade", category: "Set 15 Item" },
  { word: "Gargoyle Stoneplate", category: "Set 15 Item" },
  { word: "Infinity Edge", category: "Set 15 Item" },
  { word: "Strikers Flail", category: "Set 15 Item" },
  { word: "Spear of Shojin", category: "Set 15 Item" },
  { word: "Warmogs Armor", category: "Set 15 Item" },
  { word: "Edge of Night", category: "Set 15 Item" },
  { word: "Sunfire Cape", category: "Set 15 Item" },
  { word: "Spirit Visage", category: "Set 15 Item" },
  { word: "Jeweled Gauntlet", category: "Set 15 Item" },
  { word: "Thiefs Gloves", category: "Set 15 Item" },
  { word: "Void Staff", category: "Set 15 Item" },
  { word: "Evenshroud", category: "Set 15 Item" },
  { word: "Archangels Staff", category: "Set 15 Item" },
  { word: "Protectors Vow", category: "Set 15 Item" },
  { word: "Dragons Claw", category: "Set 15 Item" },
  { word: "Red Buff", category: "Set 15 Item" },
  { word: "Adaptive Helm", category: "Set 15 Item" },
  { word: "Hextech Gunblade", category: "Set 15 Item" },
  { word: "Bramble Vest", category: "Set 15 Item" },
  { word: "Bloodthirster", category: "Set 15 Item" },
  { word: "Morellonomicon", category: "Set 15 Item" },
  { word: "Hand Of Justice", category: "Set 15 Item" },
  { word: "Giant Slayer", category: "Set 15 Item" },
  { word: "Steadfast Heart", category: "Set 15 Item" },
  { word: "Krakens Fury", category: "Set 15 Item" },
  { word: "Steraks Gage", category: "Set 15 Item" },
  { word: "Titans Resolve", category: "Set 15 Item" },
  { word: "Last Whisper", category: "Set 15 Item" },
  { word: "Ionic Spark", category: "Set 15 Item" },
  { word: "Crownguard", category: "Set 15 Item" },
  { word: "Deathblade", category: "Set 15 Item" },
  { word: "Rabadons Deathcap", category: "Set 15 Item" },
  { word: "Blue Buff", category: "Set 15 Item" },
  { word: "Quicksilver", category: "Set 15 Item" },
  { word: "Nashors Tooth", category: "Set 15 Item" },
];

export function getRandomWord(): WordPair {
  return WORD_BANK[Math.floor(Math.random() * WORD_BANK.length)];
}